name: DonutOrder
version: '1.1.3'
main: me.clanify.donutOrder.DonutOrder
api-version: '1.21'
author: clanify
depend: [Vault]
folia-supported: true
commands:
  orders:
    usage: /orders
    aliases: [order]
  donutorder:
    usage: /donutorder reload
    aliases: [dorder, dorders]
permissions:
  donutorder.admin:
    default: op